### ISSUE TITLE
"KeyError: 'Ipwb'" on any operation

### ISSUE THREAD

**Issue by ivilata** [oduwsdl/ipwb#128]
Hi, I've followed the instructions to test ipwb and I always com across the same exception when invoking it.  For version ``0.2017.3.4.1951`` from PyPI:

```
(ipwb) $ ipwb index ipwb/samples/warcs/sample-1.warc.gz
Traceback (most recent call last):
  File "/home/ivan/env/py/ipwb/bin/ipwb", line 7, in <module>
    from ipwb.__main__ import main
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/__main__.py", line 9, in <module>
    import replay
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/replay.py", line 100, in <module>
    def getCDXJLinesWithURIR(urir, indexPath=ipwbConfig.getIPWBReplayIndexPath()):
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/util.py", line 147, in getIPWBReplayIndexPath
    if 'Index' in ipfsJSON['Ipwb']['Replay']:
KeyError: 'Ipwb'
```

For commit 03b16ed5 (current HEAD):

```
(ipwb) $ ipwb index ipwb/samples/warcs/sample-1.warc.gz
Traceback (most recent call last):
  File "/home/ivan/env/py/ipwb/bin/ipwb", line 11, in <module>
    load_entry_point('ipwb==0.2017.3.4.1951', 'console_scripts', 'ipwb')()
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/__main__.py", line 9, in <module>
    import replay
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/replay.py", line 100, in <module>
    def getCDXJLinesWithURIR(urir, indexPath=ipwbConfig.getIPWBReplayIndexPath()):
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/util.py", line 147, in getIPWBReplayIndexPath
    if 'Index' in ipfsJSON['Ipwb']['Replay']:
KeyError: 'Ipwb'
```

This happens with all calls to ``ipwb``, even ``ipwb --help``.  Thanks!

**Comment by machawk1** [comment]
@ivilata Thank you for reporting this issue. I can replicate it by nuking my `~/.ipfs`, running `ipfs init`, installing ipwb from pypi, then running `ipwb index ipwb/samples/warcs/sample-1.warc.gz`.

This likely has to do with the config being read prior to it being initialized.

**Comment by machawk1** [comment]
Upon further investigation, the `start()` function in replay invokes other functions that write the aforementioned config to `~/.ipfs/config`. This function's definition should not be in `replay.py`; `util.py` might be a better place.

**Comment by machawk1** [comment]
@ivilata This should be fixed. You should be able to install from source or update from pypi to see the issue you reported as fixed. If you still experience this issue, please re-open this ticket or comment here.

**Comment by ivilata** [comment]
I tested with commit a3b8406f and it seems to be fixed, thanks for the quick fix!
