### ISSUE TITLE
Chunked data without chunked headers causes replay to crash

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#187]
`ipwb -e myarchive.warc > myindex.cdxj` then enter key. Remove `encryption_method` and `encryption_key` fields from all CDXJ entries (find-replace). `ipwb replay myindex.cdxj` produces the following error with the replay system crashing and a "Service Unavailable" being returned to the browser on access.

```sh
[u'urn:ipfs', u'QmUmYwu1giCm1PPZfjasBkiTNDnsaUzvqx7Anx1fvWeKgP', u'QmbRgDzxcdJgeRnYLru5Fvszyz9FPNcD3p6dwFSQ3Ygrk4']
<bound method Client.cat of <ipfsapi.client.Client object at 0x103ca8dd0>>
<type 'exceptions.TypeError'>
general error
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52809)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 232, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 267, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/ipwb/replay.py", line 220, in showMementoAtDatetime
    return show_uri(urir, datetime)
  File "/usr/local/lib/python2.7/site-packages/ipwb/replay.py", line 310, in show_uri
    sys.exit()
SystemExit
----------------------------------------
127.0.0.1 - - [08/Jun/2017 16:41:45] "GET /serviceWorker.js HTTP/1.1" 200 -
```

ipwb 0.2017.06.07.1721

**Comment by machawk1** [comment]
Correction, it may be something peculiar about the WARC, attached here. Even `ipwb index 20170608203741849.warc | ipwb` returns the same error.

[20170608203741849.warc.txt](https://github.com/oduwsdl/ipwb/files/1062380/20170608203741849.warc.txt)

**Comment by machawk1** [comment]
I have narrowed the issue down to two particular problems. The line:

`payload = IPFS_API.cat(digests[-1], timeout=1)`

times out and throws a TypeError, which is odd. Can we catch this?

With the timeout removed, an error occurs on the line:
`chunkDecFromHex = int(chunkDescriptor, 16)  # Get dec for slice`. This line translates the chunked encoding to non-chunked prior to push to IPFS. The error: `invalid literal for int() with base 16:`

Replicating the capture in the aforementioned WARC with curl:

```sh
curl http:/ -iv --raw http:/www.netpreserve.org/general-assembly/2017/overview
```
shows an initial value in the payload of `008ff8`. I am unsure if this initial translation to base 16 or some offset further in the payload is causing this error.

**Comment by machawk1** [comment]
The issue, it seems, stems from IPWB pushing the HTTP headers indicating chunked data to IPFS then dechunking the payload and pushing that to IPFS. The discrepancy between HTTP headers indicating chunked and payload not being chunked causes the offset calculation to fail. A correction would be to change the header to indicate non-chunked once it has been unchunked and prior to pushing both the HTTP headers and payload to IPFS.

**Comment by machawk1** [comment]
Verified that the issue was not originally a problem, changing ticket scope.
