### ISSUE TITLE
Replay reports error when not connected to the Internet

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#269]
> ipfs version 0.4.11
InterPlanetary Wayback 0.2017.10.10.2047

Disconnect Internet connection.
Run `ipfs daemon` in one console.
Run `ipwb replay` in another console.
The below error occurs.
Reconnecting to the net, even when the ipfs is still running from the above allows ipwb to operate normally.

Error:
```
$ ipwb replay
Executing first-run procedure on provided sample data.
Processing WARC records in salam-home.warc complete
Traceback (most recent call last):
  File "/usr/local/bin/ipwb", line 11, in <module>
    load_entry_point('ipwb==0.2017.10.10.2047', 'console_scripts', 'ipwb')()
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 17, in main
    args = checkArgs(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 127, in checkArgs
    results.func(results)
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 50, in checkArgs_replay
    replay.start()
  File "/usr/local/lib/python2.7/site-packages/ipwb/replay.py", line 717, in start
    app.run(host=IPWBREPLAY_IP, port=IPWBREPLAY_PORT)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 593, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by machawk1** [comment]
Still present in InterPlanetary Wayback 0.2017.11.06.1205.

**Comment by machawk1** [comment]
From `socket.gaierror`, gai -> `getaddrinfo()`, from Flask reporting that it cannot get an IP when there's no net connection. The replay web endpoint ought to work regardless of the state of the net connection.
