### ISSUE TITLE
Cannot run ipwb on Windows

### ISSUE THREAD

**Issue by akavel** [oduwsdl/ipwb#304]
With a [workaround](https://stackoverflow.com/q/41843266/98528), as mentioned in #303, I managed to build ipwb. However, when I try to run it, I'm getting:

1. After first trying `\Python36\Scripts\pip install ipwb`:

        C:\dnload\ipfs-etc>\Python36\Scripts\ipwb.exe
        Traceback (most recent call last):
          File "C:\Python36\Scripts\ipwb-script.py", line 11, in <module>
            load_entry_point('ipwb==0.2017.12.1.11', 'console_scripts', 'ipwb')()
          File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
            return get_distribution(dist).load_entry_point(group, name)
          File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
            return ep.load()
          File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
            return self.resolve()
          File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
            module = __import__(self.module_name, fromlist=['__name__'], level=0)
          File "c:\python36\lib\site-packages\ipwb\__main__.py", line 5, in <module>
            from __init__ import __version__ as ipwbVersion
        ModuleNotFoundError: No module named '__init__'

2. After then trying a dev version d5d358d719d888126a94d01dfd3585e3d542e22f from git clone and `\Python36\Scripts\pip install ./`, the error is similar but with changed line numbers:

        C:\dnload\ipfs-etc>\Python36\Scripts\ipwb.exe replay
        Traceback (most recent call last):
          File "C:\Python36\Scripts\ipwb-script.py", line 11, in <module>
            load_entry_point('ipwb==0.2017.12.1.11', 'console_scripts', 'ipwb')()
          File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 572, in load_entry_point
            return get_distribution(dist).load_entry_point(group, name)
          File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2752, in load_entry_point
            return ep.load()
          File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
            return self.resolve()
          File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
            module = __import__(self.module_name, fromlist=['__name__'], level=0)
          File "c:\python36\lib\site-packages\ipwb\__main__.py", line 5, in <module>
            from __init__ import __version__ as ipwbVersion
        ModuleNotFoundError: No module named '__init__'

**Comment by machawk1** [comment]
@akavel We haven't completed the move over to Py3 yet per #51. If you have Python2 installed, can you repeat the above?

The import system in Py3 is a little different. Our implicit relative imports of other parts of the ipwb module within ipwb causes Py3 to choke.

**Comment by akavel** [comment]
@machawk1 Ah, oops; didn't see any info that Python 2 is required in the readme. I don't seem to have Python 2 installed but I'll try to get it then.

**Comment by akavel** [comment]
Works with Python 2. Thanks!

Maybe you could mention this in the readme till #51 is done? The error I saw didn't let me discover that the reason was Python 3, having only passing knowledge of Python at all.

**Comment by machawk1** [comment]
@akavel Will do! Thanks for giving it a spin and please continue to report any bugs you encounter.

**Comment by machawk1** [comment]
Closing this ticket with @akavel 's report of ipwb working in Py2 for Windows.
