### ISSUE TITLE
Provide further instructions for installing and usage as a binary from source

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#36]
The current state of the README recommends either installing from pip via pypi or calling the ipwb scripts directly using python. A better approach for the latter would be to install ipwb into the system using the source pulled from GitHub. The instructions on accomplishing this are not yet complete in the README and cater more to the scenario of installing via via from pypi.

**Comment by machawk1** [comment]
```sh
$ pip install -r requirements
$ pip install ./
$ ipwb
```
produces the following error:

```sh
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ipwb", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2991, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 677, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 861, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (surt 0.3b4 (/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages), Requirement.parse('surt>=0.3.0'), set(['pywb']))
```

**Comment by ikreymer** [comment]
I'm not getting the error, seems like an old surt dependency held somewhere?
i was even able to install with `pip install ipwb`, but that may be an older version?

I would recommend updating the pywb dependencies to be the regular pip release instead of the github path too

**Comment by machawk1** [comment]
@ikreymer , I only get it when installing via pip from source. The previous requirements file pulling from @rajbot's GitHub, which looked to be 0.2 whereas the latest is 0.3(b4). I'm not sure why we opted for the GH version. 

@ibnesayeed also suggested to not include the surt module as an explicit dependency, since it's probably already included w/ pywb. Is this the case? If so, I can remove it from requirements. I can also move to the pip release of pywb, as I believe you have since pushed the version from GH that had not yet been deployed to pip.

I cannot push to pypi atm, but will later tonight with the changes implemented here.

**Comment by ikreymer** [comment]
@machawk1 👍  pywb includes the proper surt dependency so yeah, i agree, you should not need to include it explicitly.

**Comment by machawk1** [comment]
This is no longer an issue. Building and running from source is sufficiently described in the README.
