### ISSUE TITLE
Only indexer is called from the ipwb binary when installed from source.

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#37]
A missing core functionality -- replay can only be invoked from source, not once installed. `ipwb (param)` indexes the WARC at param. We should introduce a --replay flag or something like it to allow the replay system to start without any further necessary params. Maybe `ipwb replay` a la MemGator instead. Thoughts, @ibnesayeed ?

**Comment by machawk1** [comment]
Also:

```sh
$ ipwb.replay
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ipwb.replay", line 11, in <module>
    load_entry_point('ipwb==0.2016.10.10.1539', 'console_scripts', 'ipwb.replay')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2604, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2264, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2274, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'
```

**Comment by machawk1** [comment]
`ipwb.replay` now invokes the replay system. `ipwb.indexer` and just `ipwb` call the indexer. Changing the ticket title.

**Comment by machawk1** [comment]
The setup file is to blame for this. Another approach would be to perform the app routing in yet-another-python file. Said file could also include the expected semantics.
```
    entry_points="""
        [console_scripts]
        ipwb = ipwb.indexer:main
        ipwb.indexer = ipwb.indexer:main
        ipwb.replay = ipwb.replay:main
    """,
```

**Comment by ibnesayeed** [comment]
I think it should be the other way where replay is given precedence as the default command. Or better yet, `ipwb` should show the help text. `ipwb index` and `ipwb replay` should work as expected, while keeping space for other sub-commands in future.

**Comment by machawk1** [comment]
@ibnesayeed I agree. We will move to `ipwb replay` to invoke the replay system `ipwb index` to be index help, `ipwb index (warcPath)` to return out the CDXJ. I will close this ticket and open another with these specifics.
