### ISSUE TITLE
Default "ipwb replay" command causes encryption error to be reported

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#460]
```
$ ipwb -v
InterPlanetary Wayback 0.2018.07.27.2357
$ ipwb replay
Executing first-run procedure on provided sample data.
Traceback (most recent call last):ome.warc: 0/4
  File "/usr/local/bin/ipwb", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 17, in main
    args = checkArgs(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 150, in checkArgs
    results.func(results)
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 56, in checkArgs_replay
    replay.start(proxy=proxy)
  File "/usr/local/lib/python2.7/site-packages/ipwb/replay.py", line 989, in start
    ipwbUtils.firstRun()
  File "/usr/local/lib/python2.7/site-packages/ipwb/util.py", line 295, in firstRun
    'radon', quiet=True)
  File "/usr/local/lib/python2.7/site-packages/ipwb/indexer.py", line 147, in indexFileAt
    warcFileFullPath, **encryptionAndCompressionSetting)
  File "/usr/local/lib/python2.7/site-packages/ipwb/indexer.py", line 230, in getCDXJLinesFromFile
    (hstr, payload, nonce) = encrypt(hstr, payload, key)
  File "/usr/local/lib/python2.7/site-packages/ipwb/indexer.py", line 81, in encrypt
    cipher = AES.new(key, AES.MODE_CTR)
  File "/usr/local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
TypeError: 'counter' keyword parameter is required with CTR mode
```

**Comment by ibnesayeed** [comment]
I think the problem is somewhere when the IPFS daemon is contacted. Objects are either not being stored properly or have issue in retrieval.

**Comment by machawk1** [comment]
This is complaining about the recent change in encryption with the update to pycryptodome. With the default WARC, we encrypt the contents. We do not need to do this but it is how it is currently done.

I am working on figuring out why testing with the same data has suddenly caused this issue to arise.

**Comment by ibnesayeed** [comment]
Maybe I am seeing a different issue then. I will investigate it further.

**Comment by machawk1** [comment]
I am also wondering if this is due to an update in pycryptodome to require this additional parameter.

**Comment by machawk1** [comment]
Setting the counter when initializing the AES object without explicitly specifying a nonce on initialization causes no value to be associated with the nonce. In the same `encrypt()` function in the ipwb indexer, when the nonce is accessed, an error is thrown saying it is not defined if the counter attribute was set on initialization.

**Comment by machawk1** [comment]
This also occurs in other usage of the encryption feature:

```py
$ ipwb index -e ipwb/samples/warcs/salam-home.warc
Enter a key for encryption: (key entered)
Traceback (most recent call last):ome.warc: 0/4
  File "/usr/local/bin/ipwb", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 17, in main
    args = checkArgs(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 150, in checkArgs
    results.func(results)
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 32, in checkArgs_index
    debug=args.debug)
  File "/usr/local/lib/python2.7/site-packages/ipwb/indexer.py", line 151, in indexFileAt
    warcFileFullPath, **encryptionAndCompressionSetting)
  File "/usr/local/lib/python2.7/site-packages/ipwb/indexer.py", line 247, in getCDXJLinesFromFile
    encrypt(hstr, payload, encryptionKey)
  File "/usr/local/lib/python2.7/site-packages/ipwb/indexer.py", line 90, in encrypt
    nonce = base64.b64encode(cipher.nonce).decode('utf-8')
AttributeError: AESCipher instance has no attribute 'nonce'
```

**Comment by machawk1** [comment]
`ipwb index ipwb/sample-warc/salam-home.warc | ipwb replay` indexes and replays as expected. `ipwb replay` alone uses the `-e` flag on the sample WARC. For now, we should disable this flag when using the same WARC by default when a user does not specify a CDXJ.

**Comment by ibnesayeed** [comment]
The problem is happening because I think by default a pre-generated CDXJ file (`sample-encrypted.cdxj`) is used which is not updated to the new style. Updating that should do the trick.

**Comment by machawk1** [comment]
Yes, and that is coupled with the encryption...the XOR version at that. I'll update this sample data very soon.

**Comment by machawk1** [comment]
@ibnesayeed I have updated the sample files and removed the behavior of the replay system encrypting by default until we get this sorted out.

9ed01a3398c4bd7cf48250466bc0e135b20b3238

**Comment by machawk1** [comment]
@ibnesayeed What do you recommend in lieu? Please try to be constructive when you criticize.

**Comment by machawk1** [comment]
Closing this ticket, as the issue in-question has been resolved. I will open another addressing the encryption issue.

**Comment by ibnesayeed** [comment]
> What do you recommend in lieu? Please try to be constructive when you criticize.

No, I was not a criticizing actually. I think it was a good thing to have something like this in the beginning as it made quick tests very handy. However, the tool is evolved since then so having a default target like this is less useful and more maintenance overhead. I will provide more feedback in #426 which is also relevant.
