### ISSUE TITLE
Unsupported locale on Android

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#602]
I am attempting to run ipwb on Android 8.1.0 via Termux and am running into an issue relating to unsupported locale (related: #21, #333, #332, #214, #99). I have started the ipfs daemon and pulled the latest ipwb source from GitHub (13eb38580746b81c5335073c0c03ec9a9306960b).

Upon running `ipwb index ipwb/samples/warcs/5mementos.warc | ipwb replay`, I get the error in the attached screenshot:

<img src="https://user-images.githubusercontent.com/2514780/51193160-31323800-18b6-11e9-9f60-b6c233ae0021.png" height="200" />

A potential caveat: I am running Python 3.7.2 (#51) via the installation command `pkg install python` then installing from the locally pulled repo source via `pip install .` instead of from pypi.

I plan on looking into this further, but please attempt to replicate this issue _then_ comment if needed.

**Comment by machawk1** [comment]
I tried a few different locales. The basis of these was the supporting listing provided by `locale.locale_alias`. These did not work but were listed:

* en_US.ISO8895-1
* english_us
* en_us
* en_US.utf8
* en_US

Setting the locale via `locale.setlocale(locale.LOC_TIME, '')` (what is current done with an empty string second argument in lieu of a system-provided locale) returns `C.UTF-8` but I am unsure if this has the intended effect that we need in setting the locale.

**Comment by machawk1** [comment]
Re-tested with latest master 63433f3 and fresh Termux.

* install ipfs 0.4.21, Python 3.7.4, and git 2.22.0 via `pkg install`
* install clang 8.0.0 via `pkg install`, required for `pycryptodome` module used in ipwb
* `git clone https://github.com/oduwsdl/ipwb; cd ipwb; pip install -r requirements.txt; pip install .`
* `ipfs init; ipfs daemon &`
* `ipwb index samples/warcs/5mementos.warc`

```
Traceback (most recent call last):os.warc: 1/8
  File "/data/data/com.termux/files/usr/bin/ipwb", line 11, in <module>
    load_entry_point('ipwb==0.2019.6.14.1328', 'console_scripts', 'ipwb')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ipwb/__main__.py", line 18, in main
    args = checkArgs(sys.argv)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ipwb/__main__.py", line 166, in checkArgs
    results.func(results)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ipwb/__main__.py", line 33, in checkArgs_index
    debug=args.debug)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ipwb/indexer.py", line 173, in indexFileAt
    warcFileFullPath, **encryptionAndCompressionSetting)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ipwb/indexer.py", line 290, in getCDXJLinesFromFile
    record.rec_headers.get_header('WARC-Date'))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ipwb/util.py", line 159, in iso8601ToDigits14
    setLocale()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/ipwb/util.py", line 139, in setLocale
    locale.setlocale(locale.LC_TIME, newLocale)
  File "/data/data/com.termux/files/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

This was a bit easier to replicate once setting up my `authorized_keys` and sshing into an Android device instead of using an on-screen keyboard.
