### ISSUE TITLE
Update usage of Python ipfsapi module to use its new name

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#608]
The Python version of the IPFSAPI has changed named from `ipfsapi` to `ipfshttpclient`. Attempting to run `ipwb` without parameters produces:

```
/usr/local/lib/python2.7/site-packages/ipwb/replay.py:15: FutureWarning: The `ipfsapi` library is deprecated and will stop receiving updates on the 31.12.2019! If you are on Python 3.5+ please enable and fix all Python deprecation warnings (CPython flag `-Wd`) and switch to the new `ipfshttpclient` library name. Python 2.7 and 3.4 will not be supported by the new library, so please upgrade.
  import ipfsapi
```
...which could probably be displayed through another means. Regardless, we should update ipwb to use the newer name for the API module.

**Comment by machawk1** [comment]
Swapping out for the updated name (from 0b9bb3ebaad36efa0d317f560a653bc6e659ad13) and running in Python 3 produces an error:

```
$ ipwb replay
Traceback (most recent call last):
  File "/usr/local/bin/ipwb", line 6, in <module>
    from ipwb.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/ipwb/__main__.py", line 9, in <module>
    from . import replay
  File "/usr/local/lib/python3.7/site-packages/ipwb/replay.py", line 47, in <module>
    from . import indexer
  File "/usr/local/lib/python3.7/site-packages/ipwb/indexer.py", line 55, in <module>
    IPFS_API = ipfsapi.Client(IPFSAPI_HOST, IPFSAPI_PORT)
  File "/usr/local/lib/python3.7/site-packages/ipfshttpclient/client/base.py", line 120, in __init__
    self._client = self._clientfactory(addr, base, **defaults)
  File "/usr/local/lib/python3.7/site-packages/ipfshttpclient/http.py", line 168, in __init__
    addr = multiaddr.Multiaddr(addr)
  File "/usr/local/lib/python3.7/site-packages/multiaddr/multiaddr.py", line 126, in __init__
    self._bytes = string_to_bytes(addr)
  File "/usr/local/lib/python3.7/site-packages/multiaddr/transforms.py", line 17, in string_to_bytes
    for proto, codec, value in string_iter(string):
  File "/usr/local/lib/python3.7/site-packages/multiaddr/transforms.py", line 55, in string_iter
    raise exceptions.StringParseError("Must begin with /", string)
multiaddr.exceptions.StringParseError: Invalid MultiAddr 'localhost': Must begin with /
```

Perhaps there was a change in the underline multiaddr implementation that prevent ipwb from using localhost on the `Client` instantiation `ipfsapi.Client(IPFSAPI_HOST, IPFSAPI_PORT)` in replay.

**Comment by machawk1** [comment]
A more fundamental example:
```
import ipfshttpclient
ipfshttpclient.Client('localhost', 9999)
```
produces the same result:
```
Traceback (most recent call last):
  File "ipfsclientest.py", line 3, in <module>
    ipfshttpclient.Client('localhost', 9999)
  File "/usr/local/lib/python3.7/site-packages/ipfshttpclient/client/base.py", line 120, in __init__
    self._client = self._clientfactory(addr, base, **defaults)
  File "/usr/local/lib/python3.7/site-packages/ipfshttpclient/http.py", line 168, in __init__
    addr = multiaddr.Multiaddr(addr)
  File "/usr/local/lib/python3.7/site-packages/multiaddr/multiaddr.py", line 126, in __init__
    self._bytes = string_to_bytes(addr)
  File "/usr/local/lib/python3.7/site-packages/multiaddr/transforms.py", line 17, in string_to_bytes
    for proto, codec, value in string_iter(string):
  File "/usr/local/lib/python3.7/site-packages/multiaddr/transforms.py", line 55, in string_iter
    raise exceptions.StringParseError("Must begin with /", string)
multiaddr.exceptions.StringParseError: Invalid MultiAddr 'localhost': Must begin with /
```

Though we are planning on decoupling ipwb from the expectation of an IPFS instance (#349), localhost has served as a sane default to get up-and-running. Some other loopback address might be appropriate to remedy the issue of accessing the local IPFS daemon, e.g., 0.0.0.0.

@ibnesayeed Your suggestion for an alternative to the above would be helpful here.

**Comment by machawk1** [comment]
Ok, simply `0.0.0.0` won't work here, needs to be a multiaddr that starts with `/` per the error message.

**Comment by machawk1** [comment]
```
IPFS_API = ipfshttpclient.Client(f"/dns/{IPFSAPI_HOST}/tcp/{IPFSAPI_PORT}/http")
```
should work as a solution for now.

**Comment by ibnesayeed** [comment]
That's a drastic change in the API. I hope they have a good reason to make such breaking changes.
