### ISSUE TITLE
Allow CDXJ piping from the indexer to replay

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#96]
The current default behavior for the indexer is to print the resulting CDXJ to stdout. Ideally, this should be able to be piped to the replay script and used as a basis CDXJ instead of relying on an external resource. This would remove the step of needing to write to disk, and potentially speed up the process.

Though this can probably be done more elegantly through inter-process communication, a good first step might be just to allow:

`ipwb index myCaptures.warc | ipwb replay`

and have replay use stdin as a fallback if no other source for the archive index is provided (or maybe, even if one is).

**Comment by machawk1** [comment]
Above currently results in:
```
Executing first-run procedure on provided sample data.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ipwb", line 11, in <module>
    load_entry_point('ipwb==0.2017.1.30.1719', 'console_scripts', 'ipwb')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipwb/__main__.py", line 16, in main
    args = checkArgs(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipwb/__main__.py", line 114, in checkArgs
    results.func(results)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipwb/__main__.py", line 36, in checkArgs_replay
    replay.start(args.index)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipwb/replay.py", line 273, in start
    app.run(host=IPWBREPLAY_IP, port=IPWBREPLAY_PORT)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 708, in run_simple
    inner()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 670, in inner
    fd=fd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 564, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 476, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
```

**Comment by machawk1** [comment]
Issue in the previous comment is due to `replay` attempting to start the daemon when it's already running. This error does not occur if `ipwb replay` is run without the piping.

**Comment by ibnesayeed** [comment]
I would vote against it. This can perhaps be handy for testing, but will have almost no practical usage. First of all, there needs to be another intermediate pipe step to sort the output of the indexer with `LC_ALL=C` locale. Secondly, input from a stream is not an effective mechanism when the next process in the pipe is going to perform binary search for each request. For toy examples it might work, but as the collection size grows, it wont scale well.

**Comment by machawk1** [comment]
@ibnesayeed 1. Get it working for toy example, 2. Make it scale.

Right now, it throws an exception if fed data on stdin.

It will be handy for testing and has practical usage for small collections and eases the burden of getting up and running for new users down to a single command (once installed) instead of a procedure.

**Comment by ibnesayeed** [comment]
This might help. http://stackoverflow.com/questions/1744989/read-from-file-or-stdin

**Comment by machawk1** [comment]
@machawk1 Disregard the above trace, I was calling replay twice instead of piping index's output to replay
Now
```sh
$ ipwb index myCapture.warc | ipwb replay
['/Library/Frameworks/Python.framework/Versions/2.7/bin/ipwb', 'replay']
```

**Comment by ibnesayeed** [comment]
By the way, you are still missing the sort step.

**Comment by machawk1** [comment]
@ibnesayeed This ticket does not involve sorting. I understand your point but it should be another ticket. There is also the issue of #92, which produces unsorted output. To accomplish this, I would rather rely on something within Python instead of UNIX command.
